### ISSUE TITLE
umap-js result change every time rerun with same parameter and dataset

### ISSUE THREAD

**Issue by Zipexpo** [PAIR-code/umap-js#38]
I understand the umap-js version needs random as init function for the position. Is there a way to avoid the random or preset the position? Could you slightly explain why the umap-js not stable as python version and what should do to overcome that?

**Comment by cannoneyed** [comment]
Hello!

So there's two things:

First, the JS version uses random embedding initialization rather than spectral embedding initialization as in python (there are certain linear algebra libraries in sklearn that aren't readily portable to JS). This could make run-to-run variation slightly higher in JS than python, though I haven't measured it.

Second, JS doesn't really give an easy way to seed the random number generator like python, so rather than exposing a `seed` parameter, I'm exposing a `random` parameter that allows you to define your own PRNG... If you'd like to have consistent runs every time, you need to supply your own PRNG (I recommend https://github.com/pigulla/mersennetwister). That way you can seed the PRNG each run and ensure that the runs are the same each time.

Hope this helps!

**Comment by zdk123** [comment]
an acceptable alternative would be a user override the initial embedding coordinates [here](https://github.com/PAIR-code/umap-js/blob/main/src/umap.ts#L807-L811), similar to how the knn graph can be set prior to InitializeFit.
