### ISSUE TITLE
Request to add transform function to transform new data after the model has been fit.

### ISSUE THREAD

**Issue by nickfrosst** [PAIR-code/umap-js#5]
It would be great if this functionality existed in the javascript implementation as it does in the python implementation here: https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L1592

**Comment by cannoneyed** [comment]
I've scoped this out and started work on it - you can track the progress [here](https://github.com/PAIR-code/umap-js/tree/transform).

The actual logic of the transform python implementation is a bit tricky, since it relies on a ton of scipy-matrix-specific conventions for shuttling the neighbor weights around... I've roughly ported over the algorithm and I'll just have to walk through its execution to make sure it's working as intended.

**Comment by nickfrosst** [comment]
Thanks so much for working on this :)

**Comment by cannoneyed** [comment]
PR [here](https://github.com/PAIR-code/umap-js/pull/6)

Mind trying this out and seeing if it all works for you?

**Comment by nickfrosst** [comment]
Oh man! Awesome! I'm at a Google offsite right now but I'll try it out as
soon as I get a chance.
